CONSOLE_ENABLE = no
COMMAND_ENABLE = no
ORYX_ENABLE = yes
RGB_MATRIX_CUSTOM_KB = yes
TAP_DANCE_ENABLE = yes
SPACE_CADET_ENABLE = no
COMBO_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes






# Custom QMK here
REPEAT_KEY_ENABLE = yes
LEADER_ENABLE = yes
